### ISSUE TITLE
Wrong capacity displayed

### ISSUE THREAD

**Issue by sebastien-prudhomme** [scaleway/scaleway-csi#17]
**Describe the bug**

Not really a bug but a strange behaviour. Perhaps related to CSI and not Scaleway driver.

As Scaleway seems to charge block-storage in SI unit, i created 2 PVC in SI Unit ("3G" instead of "3Gi", "1G" instead of "1Gi"), but when i display them with kubectl i got a wrong display of capacity:

```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM                                                                                                          STORAGECLASS   REASON   AGE
pvc-********-****-****-****-957fed0bd0f8   954Mi      RWO            Delete           Bound    elasticsearch/elasticsearch-master-elasticsearch-master-0                                                      scw-bssd                26h
pvc-********-****-****-****-9ad3e1384953   3Gi        RWO            Delete           Bound    mongodb/mongodb                                                                                                scw-bssd                2d2h
```
Seems like the capacity is rounded.

I've verified disk size on machines and all is OK with the provisioned volumes (i got 3000000000 bytes and 1000000000 bytes) 

I've tried another storageclass (not CSI) and the displayed capacity is OK:

```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM                                                                                                          STORAGECLASS   REASON   AGE
pvc-7b90cbdd-6a33-49c9-9719-f054cbcc8dcd   3G         RWO            Retain           Bound    default/test2                                                                                     local-path              16m
pvc-24fb7df9-75ef-46f4-ae94-c59f734f8e75   1G         RWO            Retain           Bound    default/test                                                                                      local-path              16m
```

**Details (please complete the following information):**
 - Scaleway CSI version: 0.1.1
 - Platform: Ubuntu 18.04
 - Orchestrator and its version: K3S corresponding to K8S 1.17.3

**Comment by Sh4d1** [comment]
Hey @sebastien-prudhomme ! I think it might be the CSI because in the driver we are using the size in bytes, so no units there. So it's either in one of the CSI sidecars, or in k8s itself. I'll try to take a look when I have some time!

**Comment by sebastien-prudhomme** [comment]
@Sh4d1 i think i found it in CSI: https://github.com/kubernetes-csi/external-provisioner/blob/3d6bea496c305929b2d9b816ed8cfdfad7e4f5ce/pkg/controller/controller.go#L689

I close the issue :-)
