### ISSUE TITLE
Missing roles for CSI resizer?

### ISSUE THREAD

**Issue by sebastien-prudhomme** [scaleway/scaleway-csi#22]
**Describe the bug**

Bug to confirm as I'm using my own Helm chart built on this repository manifests.

When launching the new CSI resizer container, got this errors in logs (the first one appears after fixing the first one):

```
E0611 15:00:16.112725       1 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:scaleway-csi:scaleway-csi-controller" cannot list resource "pods" in API group "" at the cluster scope
E0611 15:01:03.299833       1 reflector.go:380] k8s.io/client-go/informers/factory.go:135: Failed to watch *v1.Pod: unknown (get pods)
```

I had to add this in cluster roles:

```
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "watch"]
```

**Details (please complete the following information):**
 - Scaleway CSI version: 0.1.3
 - Platform:
 - Orchestrator and its version: K3S 1.17

**Comment by Sh4d1** [comment]
Hey :wave: Yep don't know how I missed this one :sweat_smile:

**Comment by Sh4d1** [comment]
Thanks for the report :smile:
