### ISSUE TITLE
Encryption support

### ISSUE THREAD

**Issue by Nox-404** [scaleway/scaleway-csi#27]
**Support for encryption**

It would be great to support volume encryption to have at-rest security over volume's content

**Describe the solution you'd like**

1. Create a `secret` with an encryption key inside
2. Refer to this secret (`[namespace]/[secret]`) and key in that secret in the `storageclass`, `pvc` or `pv`

Then:
* upon provisioning -> encrypt the volume (LUKS?)
* upon mounting -> decrypt the volume (LUKS?)

**Comment by Sh4d1** [comment]
👋 I'll try to see if I can draft a PR this week :)

**Comment by Sh4d1** [comment]
@Nox-404 still a few things to fix, but you can try it at `sh4d1/csi:enc2` if you'd like :smile:

**Comment by Sh4d1** [comment]
@Nox-404 just released [v0.1.4](https://github.com/scaleway/scaleway-csi/releases/tag/v0.1.4) with support for encrypted volumes, checkout the [guide](https://github.com/scaleway/scaleway-csi/tree/master/examples/kubernetes#encrypting-volumes) to get started and please report any issue :smile:
