### ISSUE TITLE
Memory leak in livenessprobe v2.1.0

### ISSUE THREAD

**Issue by nimoalr** [scaleway/scaleway-csi#35]
**Describe the bug**
Livenessprobe is slowly leaking memory on my Rancher cluster that use scaleway-csi. Memory on nodes is slowly being eaten up until the node run out of memory.
The issue was reported and acknowledged in [livenessprobe repository](https://github.com/kubernetes-csi/livenessprobe/issues/91) for v2.1.0 (that you're using [here](https://github.com/scaleway/scaleway-csi/blob/master/deploy/kubernetes/scaleway-csi-v0.1.5.yaml#L91) and [here](https://github.com/scaleway/scaleway-csi/blob/master/deploy/kubernetes/scaleway-csi-v0.1.5.yaml#L758)) and fixed in [livenessprobe v2.2.0](https://github.com/kubernetes-csi/livenessprobe/pull/94)

**To Reproduce**
Apply 0.1.5 yml and wait a few days. In about a week, livenessprobe will slowly eat all the available memory on a 4gb node
![image](https://user-images.githubusercontent.com/34923429/114063634-200be200-9899-11eb-8925-abf255c84e92.png)

**Expected behavior**
Livenessprobe to not leak memory, obviously. :P 

**Details (please complete the following information):**
 - Scaleway CSI version: 0.1.5
 - Platform: 
 - Orchestrator and its version: Rancher v2.5.5 + k8s v1.19.6

**Additional context**

**Comment by Sh4d1** [comment]
Hey @nimoalr ! Thanks for raising the issue, the v0.1.5 manifest is now fixed :)
