### ISSUE TITLE
Versions doesn't match between scaleway-csi-node and scaleway-csi-controller

### ISSUE THREAD

**Issue by gregorycuellar** [scaleway/scaleway-csi#52]
Version of scaleway-csi-node is v0.1.7
https://github.com/scaleway/scaleway-csi/blob/master/deploy/kubernetes/scaleway-csi-v0.2.0.yaml#L41

Version of scaleway-csi-controller is v0.2.0
https://github.com/scaleway/scaleway-csi/blob/master/deploy/kubernetes/scaleway-csi-v0.2.0.yaml#L802

As v0.2.0 has several CVEs fixed, why not use it also for scaleway-csi-node ?

**Comment by Nox-404** [comment]
Fixed the typo in https://github.com/scaleway/scaleway-csi/commit/9cfb6181792a05e691cd466eb5a1c667907dd283
