### ISSUE TITLE
Allow for volume expansion

### ISSUE THREAD

**Issue by toonsevrin** [scaleway/scaleway-csi#7]
It would be nice if the `allowVolumeExpansion` flag will be support for [volume expansion](https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/).

**Comment by jtherin** [comment]
It's planned, but scaleway block storage do not have this feature yet.

**Comment by Sh4d1** [comment]
Once it's available on block storage side, we'll implement it :smile:

**Comment by toonsevrin** [comment]
Sounds good to me! Thank you for the swift response.

**Comment by Sh4d1** [comment]
I'll close this once it's availble :smile:
